services:
  postgis:
    build: ./postgis 
    container_name: "postgis"
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "traffic"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    networks:
      - default
    restart: unless-stopped

networks:
  default:
    driver: bridge
