services:
  postgis:
    build: ./postgis 
    container_name: "postgis"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    networks:
      - default
    restart: unless-stopped

  osrm:
    image: ghcr.io/project-osrm/osrm-backend:v6.0.0
    volumes:
      - ./osrm/osm:/data
      - ./osrm/profiles:/profiles
    networks:
      - default
    ports:
      - 6000:5000
    restart: unless-stopped
    command: >
      sh -c "
      osrm-extract -p /profiles/foot.lua /data/hanoi.osm.pbf && 
      osrm-partition /data/hanoi.osrm && 
      osrm-customize /data/hanoi.osrm && 
      osrm-routed \
      --algorithm mld \
      --max-matching-size 20000 \
      --max-viaroute-size 20000 \
      --max-trip-size 20000 \
      --max-table-size 20000 \
      /data/hanoi.osrm
      "

networks:
  default:
    driver: bridge
