CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE traffic (
    id SERIAL PRIMARY KEY,
    timestamp TIMESTAMP DEFAULT NOW(),
    lat DOUBLE PRECISION,
    lon DOUBLE PRECISION,
    querypoint GEOMETRY(POINT, 4326),
    segment GEOMETRY(LINESTRING, 4326),
    data JSONB
);